// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `cua` plugin's OWN CUE schema — the typed plugin_input for the `cua`
// computer-use check/control verb AND the `kind: cua` entity body.
//
// It is the SINGLE SOURCE for this plugin's params, used two ways (the same contract
// core `spec` and every other plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline) emits ../params/cue_types_gen.go, so the provider decodes plugin_input
//     into a TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `cua:` step's plugin_input against #CuaInput.
//
// An authored `cua: <method>` step (scalar sugar) or `cua: {method: …, …}` (map form)
// desugars to the INTERNAL plugin/plugin_input envelope, and every cua-exclusive
// modifier lives HERE. The shared assertion matchers (exit_status/stdout/stderr) and
// the general `timeout` stay on core #Op, read off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone (gengotypes +
// the load-gate compile) AND splices onto the base (base ++ plugin is a def-name
// collision check, not a base-reference resolver).
type CuaInput struct {
	// method — the cua method to dispatch (also the scalar-sugar primary:
	// `cua: <method>`).
	Method CuaMethod `json:"method"`

	// --- connection -------------------------------------------------------
	// host — the deployment/venue address hosting the Cua Driver. Omitted means
	// "the deploy I am running against": the plugin drives it over the host
	// reverse channel (the venue executor), which is the normal case.
	Host string `json:"host,omitempty"`

	// driver — the `cua-driver` binary path inside the venue (default
	// /usr/local/bin/cua-driver).
	Driver string `json:"driver,omitempty"`

	// device — the name of a `kind: cua` DEVICE entity whose connection/permission
	// defaults this step inherits. Authored step fields WIN over the entity's.
	Device string `json:"device,omitempty"`

	// env — extra session environment the driver needs inside the venue (the
	// desktop-session variables). Merged over the entity's env.
	Env map[string]string `json:"env,omitempty"`

	// allow_control — REQUIRED to be true for every MUTATING method (input,
	// app control, config writes). Read-only methods ignore it. This is the
	// bed-safety gate: a live desktop is not a throwaway, and an unattended plan
	// must not type into it by accident.
	AllowControl bool `json:"allow_control,omitempty"`

	// --- input (keyboard/pointer) ----------------------------------------
	// text — the text `type` inserts.
	Text string `json:"text,omitempty"`

	// key — the named key `press-key` presses (return, escape, tab, f5, …).
	KeyName string `json:"key,omitempty"`

	// keys — the chord `hotkey` presses, e.g. ["ctrl","c"].
	Keys []string `json:"keys,omitempty"`

	// x / y — desktop-absolute pixel coordinates for click/move/scroll/drag.
	X int `json:"x,omitempty"`

	Y int `json:"y,omitempty"`

	// from_x / from_y — drag start coordinates.
	FromX int `json:"from_x,omitempty"`

	FromY int `json:"from_y,omitempty"`

	// button — pointer button (left/right/middle; default left).
	Button string `json:"button,omitempty"`

	// direction / amount — scroll direction (up/down/left/right) and notches.
	Direction string `json:"direction,omitempty"`

	Amount int `json:"amount,omitempty"`

	// pid / window_id — target a specific window for element/typed actions.
	PID int `json:"pid,omitempty"`

	WindowID int `json:"window_id,omitempty"`

	// element_index — the AX element index from a prior get-window-state.
	ElementIndex int `json:"element_index,omitempty"`

	// delivery — the Cua delivery mode for an input action: background (default)
	// or foreground. Foreground briefly fronts the window; it is the documented
	// escalation when a background action is refused or unverifiable.
	Delivery string `json:"delivery,omitempty"`

	// --- app / window -----------------------------------------------------
	// app — the app name/bundle/launch-path for launch-app.
	App string `json:"app,omitempty"`

	// window_id / value — the window a set-window-frame targets, and its value.
	Value string `json:"value,omitempty"`

	// width / height — rectangle size for set-window-frame.
	Width int `json:"width,omitempty"`

	Height int `json:"height,omitempty"`

	// --- raw escape hatch -------------------------------------------------
	// tool — the Cua Driver tool `call` invokes (any tool the plugin has not typed
	// yet). Mutating by nature, so `call` requires allow_control.
	Tool string `json:"tool,omitempty"`

	// args — the JSON object of arguments for `call`.
	Args string `json:"args,omitempty"`

	// --- artifact ---------------------------------------------------------
	// artifact — the host path `screenshot` writes the PNG to.
	Artifact string `json:"artifact,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir.
	ArtifactDir string `json:"artifact_dir,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform /
	// artifact_contains_text — the post-run artifact-reality assertions
	// (sdk.RunArtifactValidators) this verb can produce. artifact_contains_text is
	// the OCR wait-for-screen primitive in `screenshot` form (tesseract on the HOST).
	ArtifactMinBytes int `json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `json:"artifact_not_uniform,omitempty"`

	ArtifactContainsText string `json:"artifact_contains_text,omitempty"`
}

// #CuaMethod — the method catalog, grouped by intent so the read-only surface is
// separable from the mutating one (the allow_control gate).
//
// NOTE: written as a bare trailing-pipe disjunction, NOT `(...)`-wrapped: CUE does
// not terminate a parenthesised expression at a newline, so the grouped form requires
// commas and breaks `cue exp gengotypes`.
type CuaMethod string

// #CuaDeviceInput — the authored `kind: cua` DEVICE entity body: the connection and
// permission defaults a `cua:` step inherits when it names the entity with `device:`.
// One place for the driver path, the permission mode, and a default session env, so a
// bed states them once.
type CuaDeviceInput struct {
	// description — human label for the deployment/device.
	Description string `json:"description,omitempty"`

	// driver — the `cua-driver` binary path inside the venue.
	Driver string `json:"driver,omitempty"`

	// host — the deployment/venue address (omit for "the deploy I run against").
	Host string `json:"host,omitempty"`

	// permission_mode — Cua Driver's own authorization mode. `standard` is the
	// promptless default; `bounded` admits only a reviewed manifest; `unrestricted`
	// requires an explicit danger acknowledgement. The plugin passes the mode to the
	// driver's launch, never overrides a running daemon's policy.
	PermissionMode string `json:"permission_mode,omitempty"`

	// capability_manifest — the reviewed manifest path for `bounded` mode.
	CapabilityManifest string `json:"capability_manifest,omitempty"`

	// env — extra session environment the driver needs inside the venue (the
	// desktop-session variables: XDG_RUNTIME_DIR, WAYLAND_DISPLAY,
	// HYPRLAND_INSTANCE_SIGNATURE, DBUS_SESSION_BUS_ADDRESS, YDOTOOL_SOCKET).
	Env map[string]string `json:"env,omitempty"`
}
